### PR TITLE
slightly smarter inserting

### PR DESCRIPTION
**Pull request by max-mapper**
this adds to the insert logic to try and emulate how badges are included in readmes in the wild
- if a readme is not showing, it uses the current insert point (after the file list)
- if a readme is showing, it inserts the badge after the first child of the readme container
- also removes the text-align center

example:

screen shot 2014-01-08 at 10 34 02 am

### CODE REVIEW

**Comment by rvagg** [comment]
soooo.. this was the original plan but I figured that'd it'd be worth explicitly including them in all situations because: some projects only include minimal badges and I want to see everything, including dependents/dependencies, downloads and stars. Unless we parse the nodei.co url we don't know if we're dealing with just a tiny "npm install foo" badge.

I also figured that by keeping it out of the README space it serves as a reminder to authors who are using the extension that they also need to include the badges for people not using the extension. If you always look at your own libs and they have badges on all of them then it's difficult to tell whether they are there properly or not.

Thoughts?

**Comment by max-mapper** [comment]
I understand your reasoning, but personally found it to be too much of an eyesore to put them in that space between the readme and the file list. The correct solution is probably to have a config page where you can set where the badges should get inserted, and which badges should get inserted

Feel free to merge this or not, I am happy using this fork in my own Chrome for now :P

**Comment by max-mapper** [comment]
Updated this to work w/ the newer GH image proxy url rewriting, and also removed the second badge and now just show the simple badge w/ no options

**Comment by rvagg** [comment]
FYI, the download counts are broken at the moment because of npm, they're currently fixing it but I assume you remove the download stuff from your updates because it was broken.
I've put them back in the current version, assuming it'll be fixed very soon.

**Pull request merged**
